
CREATE TABLE colors (
  colorID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  colorName varchar(255),
  colorCode varchar(255),
  constraint CID primary key (colorID)

);
CREATE INDEX colors_colorName ON colors(colorName);

CREATE TABLE accessorys (
  accessoryID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  accessoryName varchar(255),
  accessoryDescription varchar(255),
  constraint AID primary key (accessoryID)
);
CREATE INDEX accessorys_accessoryName ON accessorys(accessoryName);

CREATE TABLE products (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  name varchar(255),
  description varchar(255),
  colorID INTEGER,
  weight decimal(15,2),
  price decimal(15,2),
  stock INTEGER,
  accessoryID INTEGER,
  constraint DID primary key (id),
  constraint FK_M2M foreign key (colorID) references colors (colorID)
  );
CREATE INDEX products_description ON products(description);

CREATE TABLE product_accessorys(
  tableID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  id INTEGER,
  accessoryID INTEGER,
  constraint FK_P2A foreign key (id) references products (id)
);
CREATE INDEX products_accessory_ID ON product_accessorys(tableID);




		
ALTER TABLE products_accessorys ADD FOREIGN KEY(accessoryID) REFERENCES accessorys(accessoryID);
